@extends('layouts.admin')

@section('title','Dashboard')

@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="pp-section-title mb-1">Dashboard quản trị</h1><p class="text-muted mb-0">Theo dõi hoạt động của hệ thống PitchPerfect.</p></div><div class="btn-group"><a class="btn {{ $days===30?'btn-pp':'btn-light' }}" href="{{ route('admin.dashboard',['days'=>30]) }}">30 ngày</a><a class="btn {{ $days===90?'btn-pp':'btn-light' }}" href="{{ route('admin.dashboard',['days'=>90]) }}">90 ngày</a></div></div>
<div class="row g-4 mb-4">
    @foreach([
        ['Tổng số sân',$data['totalFields'],'⚽'],['Tổng đơn đặt',$data['totalBookings'],'▣'],['Doanh thu',number_format($data['revenue'],0,',','.').' ₫','💵'],['Người dùng mới',$data['newUsers'],'♙']
    ] as [$label,$value,$icon])
        <div class="col-sm-6 col-xl-3"><div class="pp-card stat-card h-100"><div class="d-flex justify-content-between"><span class="amenity-icon">{{ $icon }}</span><span class="text-success small fw-bold">{{ $days }} ngày</span></div><div class="small text-muted text-uppercase mt-3">{{ $label }}</div><div class="stat-value">{{ $value }}</div></div></div>
    @endforeach
</div>
<div class="row g-4 mb-4"><div class="col-xl-8"><div class="pp-card p-4"><div class="d-flex justify-content-between"><h2 class="h5 fw-bold">Phân tích doanh thu</h2><span class="small text-muted">Đơn vị: VND</span></div>@php($maxRevenue=max(1,$data['dailyRevenue']->max('value')))<div class="chart-bars">@foreach($data['dailyRevenue'] as $point)<div class="chart-bar" style="height:{{ max(3,($point['value']/$maxRevenue)*100) }}%" title="{{ $point['date'] }}: {{ number_format($point['value'],0,',','.') }} ₫"></div>@endforeach</div><div class="d-flex justify-content-between small text-muted mt-2"><span>{{ $data['dailyRevenue']->first()['date'] ?? '' }}</span><span>{{ $data['dailyRevenue']->last()['date'] ?? '' }}</span></div></div></div><div class="col-xl-4"><div class="pp-card p-4 h-100"><h2 class="h5 fw-bold">Mức sử dụng sân</h2><div class="d-grid gap-3 mt-4">@forelse($data['fieldUsage'] as $field)<div><div class="d-flex justify-content-between"><span>{{ $field->name }}</span><strong>{{ $field->bookings_count }}</strong></div><div class="progress mt-1" style="height:8px"><div class="progress-bar bg-success" style="width:{{ min(100,$field->bookings_count*10) }}%"></div></div></div>@empty<p class="text-muted">Chưa có dữ liệu.</p>@endforelse</div></div></div></div>
<div class="pp-card overflow-hidden"><div class="p-4 d-flex justify-content-between"><h2 class="h5 fw-bold mb-0">Đơn đặt gần đây</h2><a href="{{ route('admin.bookings.index') }}">Xem tất cả →</a></div><div class="table-responsive"><table class="table table-pp mb-0"><thead><tr><th>Ngày</th><th>Người dùng</th><th>Sân</th><th>Khung giờ</th><th>Giá</th><th>Trạng thái</th></tr></thead><tbody>@forelse($data['recentBookings'] as $booking)<tr><td>{{ $booking->booking_date->format('d/m/Y') }}</td><td><a href="{{ route('admin.users.show',$booking->user) }}">{{ $booking->user->name }}</a></td><td>{{ $booking->footballField->name }}</td><td>{{ $booking->timeSlot->label }}</td><td>{{ $booking->formatted_price }}</td><td><x-status-badge :status="$booking->status" /></td></tr>@empty<tr><td colspan="6" class="text-center py-4">Chưa có đơn đặt.</td></tr>@endforelse</tbody></table></div></div>
@endsection
