@php($field = $field ?? null)
<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="name">Tên sân</label><input class="form-control" id="name" name="name" value="{{ old('name',$field?->name) }}" required></div>
    <div class="col-md-6"><label class="form-label" for="price_per_hour">Giá theo giờ (VND)</label><input class="form-control" type="number" min="0" id="price_per_hour" name="price_per_hour" value="{{ old('price_per_hour',$field?->price_per_hour) }}" required></div>
    <div class="col-12"><label class="form-label" for="address">Địa chỉ</label><input class="form-control" id="address" name="address" value="{{ old('address',$field?->address) }}" required></div>
    <div class="col-12"><label class="form-label" for="description">Mô tả</label><textarea class="form-control" id="description" name="description" rows="5">{{ old('description',$field?->description) }}</textarea></div>
    <div class="col-md-4"><label class="form-label" for="open_time">Giờ mở cửa</label><input class="form-control" type="time" id="open_time" name="open_time" value="{{ old('open_time',$field ? substr($field->open_time,0,5) : '06:00') }}" required></div>
    <div class="col-md-4"><label class="form-label" for="close_time">Giờ đóng cửa</label><input class="form-control" type="time" id="close_time" name="close_time" value="{{ old('close_time',$field ? substr($field->close_time,0,5) : '23:00') }}" required></div>
    <div class="col-md-4"><label class="form-label" for="status">Trạng thái</label><select class="form-select" id="status" name="status">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(old('status',$field?->status?->value ?? 'active')===$status->value)>{{ $status->label() }}</option>@endforeach</select></div>
    <div class="col-12"><label class="form-label">Tiện ích</label><div class="row g-2">@foreach(['Đèn chiếu sáng','Bãi đỗ xe','Phòng thay đồ','Nước uống'] as $amenity)<div class="col-sm-6 col-lg-3"><label class="form-check pp-card p-3"><input class="form-check-input me-2" type="checkbox" name="amenities[]" value="{{ $amenity }}" @checked(in_array($amenity,old('amenities',$field?->amenities ?? [])))>{{ $amenity }}</label></div>@endforeach</div></div>
    <div class="col-12"><label class="form-label" for="images">Tải ảnh sân</label><input class="form-control" type="file" id="images" name="images[]" accept="image/jpeg,image/png,image/webp" multiple><div class="form-text">Tối đa 10 ảnh, mỗi ảnh tối đa 4MB.</div></div>
</div>
@if($field && $field->images->isNotEmpty())
    <hr class="my-4"><h3 class="h6 fw-bold">Ảnh hiện có</h3><div class="row g-3">@foreach($field->images as $image)<div class="col-6 col-md-3"><div class="pp-card p-2"><img class="rounded mb-2" style="height:120px;width:100%;object-fit:cover" src="{{ $image->url }}"><label class="d-block small"><input type="radio" name="main_image_id" value="{{ $image->id }}" @checked($image->is_main)> Ảnh chính</label><label class="d-block small text-danger"><input type="checkbox" name="remove_image_ids[]" value="{{ $image->id }}"> Xóa ảnh</label></div></div>@endforeach</div>
@endif
<div class="mt-4 d-flex gap-2"><button class="btn btn-pp px-4" type="submit">{{ $submitLabel }}</button><a class="btn btn-light" href="{{ route('admin.fields.index') }}">Hủy</a></div>
